-- Total revenue
-- Definition:
--   Total monetary value generated by all delivered orders.
SELECT SUM(payment_value) total_revenue
FROM v_delivered_order_payments;

-- Monthly revenue
-- Definition:
--   Revenue aggregated by purchase year and month.
--   Used to analyze growth, seasonality, and trends.
SELECT YEAR(order_purchase_timestamp) `year`, MONTH(order_purchase_timestamp) `month`,
SUM(payment_value) monthly_revenue
FROM v_delivered_order_payments
GROUP BY 1, 2;

-- Monthly average order value (AOV)
-- Definition:
--   Mean payment value per delivered order by month.
--   Indicates customer spending behavior over time.
SELECT YEAR(order_purchase_timestamp) `year`, MONTH(order_purchase_timestamp) `month`,
AVG(payment_value) monthly_average_order_value
FROM v_delivered_order_payments
GROUP BY 1, 2;

-- Monthly orders
-- Purpose:
--   Identifies patterns in order volume and early adoption of the registering platform.
SELECT YEAR(order_purchase_timestamp) `year`, MONTH(order_purchase_timestamp) `month`, COUNT(order_id) number_of_orders
FROM v_delivered_orders
GROUP BY `year`, `month`;

